version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:16.13.2
    steps:
      - checkout
      - run:
          name: Set NODE_ENV to development
          command: echo "Setting NODE_ENV to development"
          environment:
            NODE_ENV: development
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Update NPM
          command: sudo npm install -g npm 
      - run:
          name: Install Dependencies
          command: npm install --only=dev
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Remove .netlify if exists
          command: |
            if [ -d "./.netlify" ]; then
              rm -r "./.netlify"
            fi
      - run: 
          name: Install netlify cli 
          command: sudo npm install netlify-cli -g
      - run:
          name: Check if netlify cli is working
          command: netlify --version
      - run:
          name: Set NODE_ENV to production
          command: echo "Setting NODE_ENV to production"
          environment:
            NODE_ENV: production
      - run:
          name: Build React App
          command: npm run build
      - save_cache:
          key: app-build-cache-{{ .Branch }}
          paths:
            - ./build
      - run:
          name: Deploy to Netlify
          command: ./node_modules/.bin/netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --prod --dir=build
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main